### ISSUE TITLE
ADD  UI  TO  list blog 

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/mns#132]
add ui  to list blogs from admin page

**Comment by idrice24** [comment]
i will use models to display it

**Comment by idrice24** [comment]
https://github.com/idrice24/mns/wiki/Documentation-and-questions

**Comment by Ghislain1** [comment]
@idrice24 works on this issue... Same as list users..

**Comment by Ghislain1** [comment]
@idrice24  any troubles?

**Comment by idrice24** [comment]
no
