### ISSUE TITLE
can't run the project

### ISSUE THREAD

**Issue by idrice24** [idrice24/mns#137]
on the development process stage the step
Run script start --> npm run start to start angular app No error? has an error

# this is the error output

C:\Users\Lenovo\Desktop\github repositaries\new datas\testall\new mns\mns>npm run start

> mns@1.0.0 start C:\Users\Lenovo\Desktop\github repositaries\new datas\testall\new mns\mns
> ng serve --open

An unhandled exception occurred: Cannot find module '@angular-devkit/build-angular/package.json'
Require stack:
- C:\Users\Lenovo\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\Users\Lenovo\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\index.js
- C:\Users\Lenovo\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js
- C:\Users\Lenovo\AppData\Roaming\npm\node_modules\@angular\cli\commands\serve-impl.js
- C:\Users\Lenovo\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Users\Lenovo\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Users\Lenovo\AppData\Roaming\npm\node_modules\@angular\cli\utilities\json-schema.js
- C:\Users\Lenovo\AppData\Roaming\npm\node_modules\@angular\cli\models\command-runner.js
- C:\Users\Lenovo\AppData\Roaming\npm\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\Lenovo\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\Lenovo\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
See "C:\Users\Lenovo\AppData\Local\Temp\ng-fCjELY\angular-errors.log" for further details.
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file C:\WINDOWS\system32\cmd.exe
npm ERR! errno ENOENT
npm ERR! mns@1.0.0 start: `ng serve --open`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the mns@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2020-10-02T16_43_40_131Z-debug.logC:\Users\Lenovo\Desktop\github repositaries\new datas\testall\new mns\mns>npm run start

> mns@1.0.0 start C:\Users\Lenovo\Desktop\github repositaries\new datas\testall\new mns\mns
> ng serve --open

An unhandled exception occurred: Cannot find module '@angular-devkit/build-angular/package.json'
Require stack:
- C:\Users\Lenovo\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\Users\Lenovo\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\index.js
- C:\Users\Lenovo\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js
- C:\Users\Lenovo\AppData\Roaming\npm\node_modules\@angular\cli\commands\serve-impl.js
- C:\Users\Lenovo\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Users\Lenovo\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Users\Lenovo\AppData\Roaming\npm\node_modules\@angular\cli\utilities\json-schema.js
- C:\Users\Lenovo\AppData\Roaming\npm\node_modules\@angular\cli\models\command-runner.js
- C:\Users\Lenovo\AppData\Roaming\npm\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\Lenovo\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\Lenovo\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
See "C:\Users\Lenovo\AppData\Local\Temp\ng-fCjELY\angular-errors.log" for further details.
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file C:\WINDOWS\system32\cmd.exe
npm ERR! errno ENOENT
npm ERR! mns@1.0.0 start: `ng serve --open`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the mns@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2020-10-02T16_43_40_131Z-debug.log

**Comment by Ghislain1** [comment]
Run npm install

**Comment by idrice24** [comment]
should i update the dev process on readme file to add this step?

**Comment by Ghislain1** [comment]
Okay  Thank you !!
