### ISSUE TITLE
Add possibility to use  Mns Angular app without backend 

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/mns#139]
Goal is simulate data from server

[Original Link ](https://angular.io/tutorial/toh-pt6#simulate-a-data-server)

**Comment by Ghislain1** [comment]
**TODOs:**
1. Enable HTTP services
1. [Enable HTTP services](https://angular.io/tutorial/toh-pt6#simulate-a-data-server)

**Comment by idrice24** [comment]
you did this part
