### ISSUE TITLE
POM ERROR

### ISSUE THREAD

**Issue by idrice24** [idrice24/MNS#14]
i have an error in my pom each  i compile or build the project:
- when i do it through CMD i have this error : [ERROR] Non-resolvable parent POM for com.idrice24:spring-boot-web:0.0.1-SNAPSHOT: Failure to find org.springframework.boot:spring-boot-starter-parent:pom2.2.6-RELEASE in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reacttemped until the update interval of central has elapsed or updates are forced and 'parent.relativPath' points at wrong location POM @ line 12, column 14 -> [Help 2]
- On IDEA InteliJ it gives me: 
java: error: release version 5 not supported

**Comment by Ghislain1** [comment]
I will pullit  and try on my local machine as soon as possible
