### ISSUE TITLE
Add Validation Registry

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/mns#140]
Read this link before implemenation, i choose the riht one
https://angular.io/guide/form-validation#validating-input-in-reactive-forms

**Comment by idrice24** [comment]
but you did it
what can i do on it again?

**Comment by Ghislain1** [comment]
I do not do it !! 
.1 Check email is missing 
1.  Check empty name is missing
Test it gain and think what is missing

**Comment by Ghislain1** [comment]
Test the web online and   write here the repro steps how to list   user after adding a new one

**Comment by Ghislain1** [comment]
NOTE: only Admin can see that list-->  What is the name of this concept in Angular?

**Comment by idrice24** [comment]
in Angular validation function is been done in two ways 
1. Sync validators: where the variable( e.g email ) is check if it null or has and error. And this return an immediate outcome 
1. Async validators: this one also check error and null value but it gives it out come when the form is validate

**Comment by Ghislain1** [comment]
Take one of your choice!! Just make it work

**Comment by Ghislain1** [comment]
@idrice24  what are condition of your validation? and how the user detect that something goes wrong

**Comment by Ghislain1** [comment]
@idrice24  I read from angular page->
easy it works fine
https://stackblitz.com/angular/gjvxvmeovjvv?file=src%2Fapp%2Freactive%2Fhero-form-reactive.component.html
watch this sample fine!!

**Comment by Ghislain1** [comment]
/ valid email pattern
   var eregex = /^([a-zA-Z0-9_\.\-\+])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
