### ISSUE TITLE
Add map inside contact page show mns237 location in douala

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/mns#151]
add reference how to use map  in angular

**Comment by idrice24** [comment]
- [ref.1](https://medium.com/@jkeung/integrating-google-maps-api-w-angular-7-e7672396ce2d)

**Comment by Ghislain1** [comment]
can you add to the project on contact page

**Comment by idrice24** [comment]
yes i will try and see

**Comment by Ghislain1** [comment]
do you have trouble here??
