### ISSUE TITLE
Configure project for Circle CI for Set up continuous integration in circleci

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/mns#162]
Reponse can be check [here - Angular Orginal](https://angular.io/guide/testing#set-up-continuous-integration)

**Comment by idrice24** [comment]
what is the use of this functionality ?

**Comment by Ghislain1** [comment]
To avoid pleople to commit bullshit !! So when the test fails, no possibility to merge..
@idrice24 read the link you will get answer of you question

**Comment by Ghislain1** [comment]
the first sentence says everything .
_One of the best ways to keep your project bug-free is through a test suite, but it's easy to forget to run tests all the time. Continuous integration (CI) servers let you set up your project repository so that your tests run on every commit and pull request._

**Comment by Ghislain1** [comment]
test with krama works but not e2e tets new issue
