### ISSUE TITLE
Running problems

### ISSUE THREAD

**Issue by idrice24** [idrice24/mns#165]
i can run the task ''npm run start'' successfully 
when i do, i have the following problem 

C:\Users\Lenovo\Desktop\github repositaries\new datas\testall\new mns\mns>ng serve
An unhandled exception occurred: Script file node_modules/popper.js/dist/umd/popper.js does not exist.
See "C:\Users\Lenovo\AppData\Local\Temp\ng-OSspUL\angular-errors.log" for further details.

C:\Users\Lenovo\Desktop\github repositaries\new datas\testall\new mns\mns>npm run start

> mns@1.0.0 start C:\Users\Lenovo\Desktop\github repositaries\new datas\testall\new mns\mns
> ng serve --verbose  --open

An unhandled exception occurred: Script file node_modules/popper.js/dist/umd/popper.js does not exist.
See "C:\Users\Lenovo\AppData\Local\Temp\ng-frEUmU\angular-errors.log" for further details.
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file C:\WINDOWS\system32\cmd.exe
npm ERR! errno ENOENT
npm ERR! mns@1.0.0 start: `ng serve --verbose  --open`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the mns@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2020-10-04T09_41_38_767Z-debug.log

**Comment by Ghislain1** [comment]
Try npm installl

**Comment by Ghislain1** [comment]
So kind of error , which stops to you work,  you have to write whatsapp message!!

**Comment by Ghislain1** [comment]
Can you run? @idrice24

**Comment by idrice24** [comment]
not yet
i have clone it back and the npm install is still running

**Comment by idrice24** [comment]
it is ok now 
it has run
