### ISSUE TITLE
Add home icon near home menu on main page

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/mns#169]
Add home icon.. Class="icon-???" on html file.. Same like font awesone!!

**Comment by idrice24** [comment]
i dont understand and where i have to put the icon

**Comment by Ghislain1** [comment]
![image](https://user-images.githubusercontent.com/13945825/95088566-67b38480-0723-11eb-9507-ab82ba1e143a.png)


see pic

**Comment by Ghislain1** [comment]
@idrice24  Good luck
