### ISSUE TITLE
Missing search page on the app

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/mns#182]
App should display a page with list of  topics or services when user press search buttons  from home page --> search should get his own **module, components and service**

**Comment by idrice24** [comment]
ok

**Comment by idrice24** [comment]
please can you explain to me how do it or give me some ref..

**Comment by Ghislain1** [comment]
Add  page to appear when a user search something from home page

**Comment by Ghislain1** [comment]
Icon for search is wrong in hOME PAge_
