### ISSUE TITLE
Big bug app does not work anymore on cloud 

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/mns#186]
@idrice24 why this bug?? I told you 200000 times..
Respect développement process
Run deploy. Cmd file before commit

**Comment by idrice24** [comment]
i am just from running it 
it works!!!!!!!!!!!!!!

**Comment by idrice24** [comment]
what is the error on the screen?

**Comment by Ghislain1** [comment]
ReproTstep:
1. Open Mns from browser --> Open successfully
2.  Press redirect button (near home icon)  to reload the page manually --> page 404  appears 
3. @idrice24  This error  is deja vu!!
