### ISSUE TITLE
pom file should be commented

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/MNS#19]
comments **_each dependencies_** in pom file !!

with your own short sentences  ----  the comments should **inside the pom** file

**example**:
<  !--  COMMENTS:  for what , goals, needed ..  short sentenceto explain    - >
	< dependency>
			<  groupId>org.springframework.session</groupId>
			<  artifactId>spring-session-core</artifactId>
		<   /dependency>

**Comment by idrice24** [comment]
i have complete it
