### ISSUE TITLE
Login page gets error

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/mns#191]
See picture
![image](https://user-images.githubusercontent.com/13945825/95716861-624ac280-0c6c-11eb-8cf9-241145271b73.png)

See Your school management system how login page is designed -

**Comment by idrice24** [comment]
to show that zou are out no in

**Comment by Ghislain1** [comment]
_to show that zou are out no in_ : if you are out --> login page is shown,  if you are in --> another page is shown i.e.  admin page

We DO NOT Need that--  what we need is message for  **validation** when something goes wrong
