### ISSUE TITLE
Setting up Angular Google Maps in Contact page

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/mns#201]
@idrice24  I  found a component which can  be used  for our map in contact

Do you have any ApiKey?

https://angular-maps.com/guides/getting-started/

**Comment by idrice24** [comment]
no 
i dont have an ApiKey
any idea how to get it?

**Comment by Ghislain1** [comment]
@read the message on top  to get how to get it
READ READ___ READ __ READ __READ

**Comment by Ghislain1** [comment]
Di
