### ISSUE TITLE
Java Style should we use ?

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/MNS#22]
Complete the list of java style:
1. [Maven Code Style ](https://maven.apache.org/developers/conventions/code.html) - [Xml  for IDE](https://maven.apache.org/developers/maven-idea-codestyle.xml)
1. [google-java-format](https://github.com/google/google-java-format) - [ Specification](https://google.github.io/styleguide/javaguide.html)  - [code sample](https://developers.google.com/style/code-samples)

We have to take one of them!!

**Comment by idrice24** [comment]
ok Maven Code Style - Xml for IDE
