### ISSUE TITLE
Login in get error

### ISSUE THREAD

**Issue by idrice24** [idrice24/mns#239]
i can't login on cloud . when i end my criterial then press submit button no reaction.
help???

**Comment by Ghislain1** [comment]
Login works fine : user name is admin and password is admin

**Comment by Ghislain1** [comment]
DO NOT Use autocomplete of browseer

**Comment by Ghislain1** [comment]
Should i close this issue ?

**Comment by Ghislain1** [comment]
test  lofin in cloud and let me know

**Comment by idrice24** [comment]
not yet

**Comment by Ghislain1** [comment]
What s wrong ??

**Comment by Ghislain1** [comment]
Press Login:
from app
 and enter admin  admin

**Comment by idrice24** [comment]
it ok you can close it
