### ISSUE TITLE
Upgrade project to use sass for style file 

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/mns#242]
https://stackoverflow.com/questions/40726081/angular-cli-from-css-to-scss
rename all css fiel to scss file !!

**Comment by idrice24** [comment]
to update it type the following command
## ng g schematics-scss-migrate:scss-migrate
this will do the following set auto.
- Renamed all the stylesheets in the src folder recursively.
- Altered the styleUrls value to point to the new file names for the stylesheet in the component classes relative to the component style files.
- Updated the component styles schematics value in the angular.json file or creates one if the schematic does not exist.
- And renamed styles.css references to .scss in the angular.json file

**Comment by idrice24** [comment]
[ref](https://medium.com/@ngubanethabo.ambrose/migrate-from-css-to-scss-stylesheets-for-existing-angular-application-d61f8061f5b7)

**Comment by Ghislain1** [comment]
I got error

**Comment by Ghislain1** [comment]
Can you do it for me ?

**Comment by idrice24** [comment]
i too
 we have to go manually

**Comment by Ghislain1** [comment]
I got issue for that

**Comment by Ghislain1** [comment]
I willclose this own-- we have to reduce issues as soon as possible
