### ISSUE TITLE
Due to upgrade to scss file -- @idrice update all css file to scss 

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/mns#244]
Not in node-module folder
Check angular,json file if configure scss for style?

**Comment by Ghislain1** [comment]
ng g schematics-scss-migrate:scss-migrate
this will do the following set auto.

Renamed all the stylesheets in the src folder recursively.
Altered the styleUrls value to point to the new file names for the stylesheet in the component classes relative to the component style files.
Updated the component styles schematics value in the angular.json file or creates one if the schematic does not exist.
And renamed styles.css references to .scss in the angular.json file

**Comment by idrice24** [comment]
ok
