### ISSUE TITLE
Admin Side bar menu should uses primeng component

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/mns#282]
choose a suitabe sidebar menu for admin side bar menu

this should be  fixed
![image](https://user-images.githubusercontent.com/13945825/97210101-67a42300-17bd-11eb-846b-10e9607a8e1a.png)

**Comment by idrice24** [comment]
Any ref ?

**Comment by Ghislain1** [comment]
checko primeng template

**Comment by Ghislain1** [comment]
https://www.primefaces.org/showcase/
