### ISSUE TITLE
Hosting Web in Firebase

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/mns#296]
**Deploy to GitHub pages** (Should moove to wiki if correct for U)
 1.  Setting Up a Firebase Deployment 
      1. A
1. Run Command sequencely
    1.  firebase login
    1.  firebase init
    1.  Under folder public paste the output result from (ng build --prod)
     1. firebase deploy

**Comment by idrice24** [comment]
i tought that firebase will help us only for the api side

**Comment by idrice24** [comment]
please some references??

**Comment by Ghislain1** [comment]
For forebase i m going to do it
