### ISSUE TITLE
Configuring SCM im pom file

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/MNS#30]
What is the purpose  of that?

[ Ref](https://maven.apache.org/scm/maven-scm-plugin/usage.html)

**Comment by idrice24** [comment]
done!
https://maven.apache.org/scm/maven-scm-plugin/examples/bootstrapping-with-pom.html
SCM is a Software Configuration Management version that help to check the healthiness of your project for example when you are using bootstrapping your project.
