### ISSUE TITLE
You can write those people to gets advice from them or looking for opportinuties

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/mns#304]
Many People are on your page and look at her website with porto folio --> exactly you have to react

Write then about job,  we don t need to travel to get nice job...

**IDRICE YOU HAVE TO THINK BYYOURSELF TO CHANGE YOUR LIFE:**

![image](https://user-images.githubusercontent.com/13945825/97846375-34e2b900-1cee-11eb-92c2-6668b1a1a5c6.png)

**Comment by idrice24** [comment]
it is not easy as you think
here the country is not the same as in the passed.
even if you are good in what you are doing they will not take except you have someone in that company who have a high post.
it is why most of us want to go out.
you can see the example  from the Cameroon police web site.

**Comment by Ghislain1** [comment]
Who told you that it s  going to be easy!!..
I have many Friends in cammeroon  they works in big compagny without VITAMIN D; C..
You have to manage more ... 
AND think by yourself.. YOU have many opportinuties  BUT it s seem like you are going to spoil it.

**Comment by Ghislain1** [comment]
For examples: 
1. We are working on project over 3 months--> you never add an issue(suitable of project), no question about stack
1. Where do you protocol your work? your experience  such as git, angular, primeng : i have my own my boss here in german gets its own
1. YOU Dont like to read --> coding is not all ( think about interview)
1. NO suggestion from U--> only scss and github check stuffs
