### ISSUE TITLE
Which platform should we choose for continuous inspection of code quality? 

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/mns#31]
Complete the list with their own search
1.  [SonarQube](https://www.sonarqube.org/)
     * What: plaform to manage CQ
     * Open source --> free
     * formerly Sonar

**Comment by idrice24** [comment]
1. crucible
     - high quality code
     - free-> 30gays
2. Upsource
  - project review
  - code analysis 
  - not free
3. review board
    - not free

**Comment by Ghislain1** [comment]
Why do you close issue ??  you have to take decision first ...
keep this on mind !! we are lloking for free stuffs
