### ISSUE TITLE
Commits behind master

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/mns#311]
When you got a number  like in pic : you should synchronize your local CODE with master --> Seee my wiki on mns237-bankend if you don t konw how to sync master!!

What mean   that number 4 in pic?

![image](https://user-images.githubusercontent.com/13945825/98024304-69e32e80-1e08-11eb-8fe6-08fcea1a4524.png)

**Comment by Ghislain1** [comment]
You can avoid some thing conflicts and many wrong push

**Comment by idrice24** [comment]
That I am 4 commit behind the master

**Comment by Ghislain1** [comment]
Master gets 4 Commits, which you don t have in branch !!--> Risk of conficts or overritten stuffs in master

--@Idrice : your answer  should be with your own word!!!

**Comment by Ghislain1** [comment]
!! --
