### ISSUE TITLE
Admin Should use the Init SIDE bar in code and PRIMENG Component

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/mns#315]
Todo!
1. I created a component  sidebar (It is empty)
1. Use Only primeng  to implemnet sidebar
1. Many examples:
   *  https://www.primefaces.org/roma-ng/#/ --> JUST sidebar with icon and tooltip
   * https://www.primefaces.org/roma-ng/#/uikit/menu --> MegaMenu - Vertical
   *  https://www.primefaces.org/manhattan-ng/#/ --> With Animation difficult for me!!
   * https://www.primefaces.org/ultima-ng/#/ --> No animation  and look good  difficult forme
![image](https://user-images.githubusercontent.com/13945825/98044269-e71d9c00-1e26-11eb-9775-2f16eb94ea75.png)

**Comment by Ghislain1** [comment]
https://github.com/idrice24/mns/blob/master/src/app/shared/components/side-bar/side-bar.component.html
@idrice24  uses this one

**Comment by Ghislain1** [comment]
https://github.com/ganatan/angular10-app/blob/master/frontend/src/app/app.component.html
A reference project using nice css of bootstrap for side bar @idrice24  good luck

**Comment by idrice24** [comment]
i am not understanding 
this side bar is for the admin or for both the user and admin?

**Comment by idrice24** [comment]
i am not understanding 
this side bar is for the admin or for both the user and admin?

**Comment by Ghislain1** [comment]
Just for admin now !! But as own component --> Admin html should just use it as html

**Comment by idrice24** [comment]
What shpuld the sidebar contain?

**Comment by Ghislain1** [comment]
Sams as before!!!

**Comment by Ghislain1** [comment]
Same as before

**Comment by idrice24** [comment]
should i used that empty sidebar or i modify this one?
the one that you have created is not show on browser
