### ISSUE TITLE
Login page is catastroph .. Look at registry page 

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/mns#326]
![image](https://user-images.githubusercontent.com/13945825/98296265-f598be80-1fb2-11eb-8d37-f88e06d66362.png)

**Comment by idrice24** [comment]
i told you that using primeNG here will not be good. 
that we have to design it on our own. since two days that i am looking a best primeNg to use.

**Comment by Ghislain1** [comment]
Look at registry component!!  Same thing and just replace naming there : Write you own protocol.. 
Shoud be done today..... You are terrible..
