### ISSUE TITLE
Relationship / Structure of Models In Whole App

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/mns#369]
Can you design the  structure of  Model using main properties
Topic --> Comment [] : This means topics gets many comments and Comment is interface
Topic  --> Author : This means knows his authors and Author  is interface

REFERENCE1
https://github.com/gothinkster/angular-realworld-example-app/blob/master/src/app/core/models/article.model.ts
https://angular.realworld.io/register --> Look and Feel it
Article --> tagList[]
Article --> Author : This means knows his authors and Author  is interface

**Comment by idrice24** [comment]
the author is the name of the person who is reacting on the blog

**Comment by idrice24** [comment]
this link is not openning https://angular.realworld.io/register

**Comment by Ghislain1** [comment]
even for me

**Comment by Ghislain1** [comment]
Just a demo app but you can see the source code
