### ISSUE TITLE
Language specification ?

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/MNS#37]
Todos:
1. List components that we need   for implementing English and French in platform
1. Provide 2 sample projects for this purpose here
1. This is NOT AN  ISSUE for implementation

**Comment by idrice24** [comment]
ok but the project can be use in English and french 
it will depend on the browser of the user. if the user uses a french browser to open our web site the the browser will automatically ask him if he want to translate this to french.
not need to have two sample else the client want the two
