### ISSUE TITLE
[Actu] post-details should display image when  seleted

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/mns#377]
![image](https://user-images.githubusercontent.com/13945825/101518968-e24a8b80-3982-11eb-9e70-8d977b237a1f.png)

**Comment by Ghislain1** [comment]
@idrice24  if you fixed . then close this issue

**Comment by idrice24** [comment]
i fixed it but it is not giving on the cloud
i will trz it back again

**Comment by Ghislain1** [comment]
Check Image URL for Blog object

**Comment by Ghislain1** [comment]
@idrice24 DO NOT forget to Test reponsive of image in Detail Blog page

**Comment by idrice24** [comment]
Ok
