### ISSUE TITLE
Web App does not display landing by first start

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/mns#381]
From read me klick --> Live App
expected: should display landing page

![image](https://user-images.githubusercontent.com/13945825/101909241-7ef86d80-3bbd-11eb-8dcb-60080a2ba5d4.png)

**Comment by idrice24** [comment]
I am just from clicking on the button ,
The landing page is given the product page first

**Comment by Ghislain1** [comment]
We can close this issue
