### ISSUE TITLE
[Actu] should display tooltip with word comments over icon

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/mns#396]
USE Primeng TOOLTIP  , and strategy to add Module (externe Module) 

![image](https://user-images.githubusercontent.com/13945825/102524271-08fe7580-4099-11eb-9e94-f91b27093515.png)

**Comment by idrice24** [comment]
I am not understanding what to dohere

**Comment by Ghislain1** [comment]
icon should provide a tooltip

**Comment by Ghislain1** [comment]
see my cart icon in product list...  mouseover on it you see tooltip

**Comment by Ghislain1** [comment]
Or here 
https://medium.com/@markathompson
