### ISSUE TITLE
Explain theses attacks Injections, XSS  and CSRF 

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/MNS#40]
Todos:
1. List a reference for reading
1. List sample projects which secure his app against these attakts
1. Explain with your own word!!

**Comment by idrice24** [comment]
1) Injections attacks  refer to a broad class of attack verctors. in an injection attack, an attacker supplies entrusted input to a program. This input helps processed by an interpreter as part of a command or query.

2) XSS (cross site scripting ) is a common attack vector that injects malicious code into a vulnerable web application.

3) CSRF the attacker causes the victim user to carry out an action unintentionally. e.g this maybe change the email address on their account, to change the passord, or to make a funds transfer.
