### ISSUE TITLE
[Actu] Tooltip appears far away from icon AND Comments in french

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/mns#403]
![image](https://user-images.githubusercontent.com/13945825/102694953-acc85c80-4224-11eb-9ac9-9da0a13b5c1b.png)

**Comment by idrice24** [comment]
Where should I put it??

-----Message d'origine-----
De : "Ghislain" <notifications@github.com>
Envoyé : ‎19/‎12/‎2020 18:05
À : "idrice24/mns" <mns@noreply.github.com>
Cc : "idrice24" <idrice.tsafouet@yahoo.com>; "Assign" <assign@noreply.github.com>
Objet : [idrice24/mns] [Actu] Tooltip appears far away from icon (#403)

**Comment by Ghislain1** [comment]
Bulshit !!! Have you never see Tooltip ?? Put directly into  icon

**Comment by idrice24** [comment]
Meaning not on the number!!

-----Message d'origine-----
De : "Ghislain" <notifications@github.com>
Envoyé : ‎20/‎12/‎2020 19:13
À : "idrice24/mns" <mns@noreply.github.com>
Cc : "idrice24" <idrice.tsafouet@yahoo.com>; "Assign" <assign@noreply.github.com>
Objet : Re: [idrice24/mns] [Actu] Tooltip appears far away from icon AND Comments in french (#403)

Bulshit !!! Have you never see Tooltip ?? Put directly into icon

**Comment by Ghislain1** [comment]
Check it product module .. on  Add to Chart

**Comment by Ghislain1** [comment]
DONE

**Comment by idrice24** [comment]
I can't test the apps on cloud ☁ why?
The actuallite page does not open!!

-----Message d'origine-----
De : "Ghislain" <notifications@github.com>
Envoyé : ‎22/‎12/‎2020 12:35
À : "idrice24/mns" <mns@noreply.github.com>
Cc : "idrice24" <idrice.tsafouet@yahoo.com>; "Assign" <assign@noreply.github.com>
Objet : Re: [idrice24/mns] [Actu] Tooltip appears far away from icon AND Comments in french (#403)

Closed #403.
