### ISSUE TITLE
Set the document title  

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/mns#408]
repro:
 Open the app --------> Click on any Tab -----> The document title should update according to tab name see pic
Ref: https://angular.io/guide/example-apps-list

![image](https://user-images.githubusercontent.com/13945825/102785120-bcb77c00-439d-11eb-9f06-b582f09fb15f.png)

**Comment by idrice24** [comment]
What should I do here??

-----Message d'origine-----
De : "Ghislain" <notifications@github.com>
Envoyé : ‎21/‎12/‎2020 15:05
À : "idrice24/mns" <mns@noreply.github.com>
Cc : "Subscribed" <subscribed@noreply.github.com>
Objet : [idrice24/mns] Set the document title   (#408)

repro:
Open the app --------> Click on any Tab -----> The document title should update according to tab name see pic
Ref: https://angular.io/guide/example-apps-list

**Comment by Ghislain1** [comment]
do you know where document title is?
