### ISSUE TITLE
[Actu] Find the way   to go to NEXT or Preview  topic from detail-topic page

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/mns#410]
see Dgsn Police page for design and Idea

**Comment by idrice24** [comment]
Ok

-----Message d'origine-----
De : "Ghislain" <notifications@github.com>
Envoyé : ‎21/‎12/‎2020 15:25
À : "idrice24/mns" <mns@noreply.github.com>
Cc : "idrice24" <idrice.tsafouet@yahoo.com>; "Assign" <assign@noreply.github.com>
Objet : Re: [idrice24/mns] [Actu] Find the way   to go to NEXT or Preview  topic from detail-topic page (#410)

Assigned #410 to @idrice24.
