### ISSUE TITLE
Set the document title  for  Bog page -- @Idrice Contact and Produits has been done

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/mns#414]
Test it:
* Browser the app
* See the title on the tab header : **MNS 237**
* Select Actualites ----> you should see **MNS 237 - Actualites** 
*

Same test for contact --> You seen   **MNS 237 - Contact**

**Comment by idrice24** [comment]
this is a problem on the cloud 
i can test the app on cloud for ( Actualites and MNS and Contact ). when i click on it it does not open .

**Comment by Ghislain1** [comment]
Check you job email

**Comment by idrice24** [comment]
done

**Comment by Ghislain1** [comment]
what means Done when you check your email job?

**Comment by Ghislain1** [comment]
https://idrice24.github.io/mns/contact --> on Clound working fine

**Comment by idrice24** [comment]
i am checking it and i am seeing an respond from one company (Khalifa Building office No.105, same building of Al Raha Furniture Al Istaqlal Street beside Pan Gulf Furniture on Main Road Abu Shagara Sharjah) that i should come with my CV, PASSPORT copy, VISA copy at this company

**Comment by Ghislain1** [comment]
you have to search information abut those compagnies --> i will ask you question through channel phone

**Comment by idrice24** [comment]
oK i am doing it
    On Tuesday, December 22, 2020, 12:23:21 PM GMT+1, Ghislain <notifications@github.com> wrote:  
 
 


Test it:
   
   - Browser the app
   - See the title on the tab header : MNS 237
   - Select Actualites ----> you should see MNS 237 - Actualites
   - 

Same test for contact --> You seen MNS 237 - Contact
