### ISSUE TITLE
[BUG] Init Backend is wrong :-1

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/MNS#42]
@idrice24  i gave you reference how to init REST API with spring boot

https://spring.io/guides/tutorials/rest/

READ from top until botton and understand what happen there :

**Comment by idrice24** [comment]
ok but my problem is that 
i can't  yet compile the project on my computer. 
i am still facing this problem of pom

[ERROR] Failed to execute goal on project spring-boot-web: Could not resolve dependencies for project com.idrice24:spring-boot-web:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at org.springframework.data:spring-data-rest-hal-explorer:jar:3.3.3.RELEASE: Failed to read artifact descriptor for org.springframework.data:spring-data-rest-hal-explorer:jar:3.3.3.RELEASE: Could not transfer artifact org.springframework.data:spring-data-rest-hal-explorer:pom:3.3.3.RELEASE from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/springframework/data/spring-data-rest-hal-explorer/3.3.3.RELEASE/spring-data-rest-hal-explorer-3.3.3.RELEASE.pom: Unknown host repo.maven.apache.org -> [Help 1]

**Comment by Ghislain1** [comment]
You have to read fine: **Could not transfer artifact org.springframework.data:spring-data-rest-hal-explorer:pom:3.3.3.RELEASE from/to central** 
This means 
1. central does not contain that dependency --> go to your website and check by yourself
1. Typo error on dependency name --> this is not our case
1. central does not contain that dependency version --> go to your website and check by yourself

this is a link to make it work:
https://github.com/spring-guides/tut-rest/blob/master/rest/pom.xml
**from**  https://spring.io/guides/tutorials/rest/

**Comment by idrice24** [comment]
the POM is not still given

**Comment by Ghislain1** [comment]
What is the error ?  
you have to run batch file -- See  Read me file development process  of server
