### ISSUE TITLE
Update All packages and angular package to 11 

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/mns#421]
https://update.angular.io/?v=10.0-11.0

**Comment by idrice24** [comment]
Meaning that I have to update my machine angular version too..

-----Message d'origine-----
De : "Ghislain" <notifications@github.com>
Envoyé : ‎28/‎12/‎2020 11:36
À : "idrice24/mns" <mns@noreply.github.com>
Cc : "Subscribed" <subscribed@noreply.github.com>
Objet : [idrice24/mns] Update package and angular papage to 11  (#421)

https://update.angular.io/?v=10.0-11.0

**Comment by Ghislain1** [comment]
If you want

**Comment by Ghislain1** [comment]
can you build the project without updating??

**Comment by Ghislain1** [comment]
Accept the PR..  Add your comments or question before : Any Question  DO NOT ACCEPT PR

**Comment by idrice24** [comment]
Ok

-----Message d'origine-----
De : "Ghislain" <notifications@github.com>
Envoyé : ‎28/‎12/‎2020 23:35
À : "idrice24/mns" <mns@noreply.github.com>
Cc : "idrice24" <idrice.tsafouet@yahoo.com>; "Comment" <comment@noreply.github.com>
Objet : Re: [idrice24/mns] Update All packages and angular package to 11  (#421)

If you want

**Comment by idrice24** [comment]
I have not yet pull it 

-----Message d'origine-----
De : "Ghislain" <notifications@github.com>
Envoyé : ‎28/‎12/‎2020 23:36
À : "idrice24/mns" <mns@noreply.github.com>
Cc : "idrice24" <idrice.tsafouet@yahoo.com>; "Comment" <comment@noreply.github.com>
Objet : Re: [idrice24/mns] Update All packages and angular package to 11  (#421)

can you build the project without updating??

**Comment by Ghislain1** [comment]
You cannot pull because PR not accepted

**Comment by Ghislain1** [comment]
_Good Morning Madam/Sir,
    here are my Documents Require for the job application.
And For my Visa Copy i don't yet have.
thanks!!_


NOT Correct: you have to take with format: You have to form sentence fine  and take care pointuation and respect :: Those people are not your friend
