### ISSUE TITLE
[Actu]  Add suitable data for actualites with categories

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/mns#424]
Data  missing categories such as products, news

![image](https://user-images.githubusercontent.com/13945825/103356024-1a3f7d00-4ab0-11eb-8370-f9ec0be45fc7.png)

**Comment by idrice24** [comment]
Yes

-----Message d'origine-----
De : "Ghislain" <notifications@github.com>
Envoyé : ‎30/‎12/‎2020 15:04
À : "idrice24/mns" <mns@noreply.github.com>
Cc : "idrice24" <idrice.tsafouet@yahoo.com>; "Assign" <assign@noreply.github.com>
Objet : [idrice24/mns] [Actu]  Add suitable data for actualites with categories (#424)

Data missing categories such as products, news
