### ISSUE TITLE
Blog display wrong view after new post

### ISSUE THREAD

**Issue by idrice24** [idrice24/mns#445]
@Ghislain1 !!!
- the post content is empty after new post was created
- the title display wrong postion
- lier plus can not work on new post 
- we can not comment on new post
![CaptureBlog](https://user-images.githubusercontent.com/50774032/109367766-48b2bc00-7897-11eb-9da9-ac5e10cc0ef4.PNG)

**Comment by Ghislain1** [comment]
maybe the post gets no content!!
