### ISSUE TITLE
Update package.json

### ISSUE THREAD

**Issue by idrice24** [idrice24/mns#450]
Name: @angular/cdk version: 11.0.3->11…2.3
Name: @angular/CLI version: 11.0.5->11.2.6
Name: @angular/core version: 11.0.5->11.2.7
Ñame: rxjs version: 6.6.3->6.6.6

**Comment by Ghislain1** [comment]
Okay !! Nice idea

**Comment by Ghislain1** [comment]
@idrice24  done?  can we close this issue?

**Comment by Ghislain1** [comment]
Done! i  checked it
