### ISSUE TITLE
Add Angular sample project 

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/MNS#46]
List a reference project by using angular and links!!
1. [Project structure]()
1. [Starter  Angular 10+](https://github.com/ganatan/angular-example-starter)
1. [Internationalization (i18n)](https://angular.io/guide/i18n#translate-text-not-for-display)
1. [Origin Angular](https://angular.io/)

**Comment by idrice24** [comment]
1. Project Structure ( https://angularbites.com/building-an-enterprise-grade-angular-project-structure/)
2. Start Angular 10+ ( https://github.com/truonghungit/angular-starter )
3. Internationalization (i18n) ( https://angular.io/guide/i18n )
4. Origin Angular (https://www.journaldunet.fr/web-tech/developpement/1441189-comment-integrer-une-requete-cors-dans-un-header-avec-angular/)
