### ISSUE TITLE
Upgrade  Angular to 10+

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/MNS#47]
1. Upgrade angular project to  version 10+
1. Details of repro step should be added here
1. [Read it](https://update.angular.io/)

**Comment by idrice24** [comment]
1. to update angular version of your apps you must first of all check the actual version and if it is less than v9 and you want 
update it to v10 don't go directly to v10 you most gostep by step ie version after version before attending v10

**Comment by idrice24** [comment]
We analyzed your package.json, there are some packages to update:

      Name                               Version                  Command to update
     --------------------------------------------------------------------------------
      @angular/cli                       9.1.12 -> 10.1.1         ng update @angular/cli
      @angular/core                      9.1.12 -> 10.1.1         ng update @angular/core
      rxjs                               6.5.5 -> 6.6.3           ng update rxjs
