### ISSUE TITLE
Respect architecture of frontend --> wrong place for custom stuffs

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/MNS#57]
https://github.com/idrice24/MNS/blob/master/documents/imgs/App_compliant_folder_file_structure.JPG

1.. Custom.ts should be in shared module under Models folder
1. Service(Common service) should be in shared module under Service folder

Same approch should be done also in backend!!

**Comment by idrice24** [comment]
the files have been corrected. thanks!!
