### ISSUE TITLE
[High prior] GitHub Pages for prototyp gets error

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/MNS#58]
@idrice24 
* **This is a desaster:**   before  push some thing  you have to make sure that it  works!!!

* Checklist  of definition of done backend  and fontend shoul be done and add it to readme .md file

***************************
Checklist of frontend
****************************
1. Synchronized  with master  - successful ?
1. Make your change 
1. Run a web api server - successful ?
1. Run start script - successful ?
1. Run deploy script - successful ?
1. Commit with **issue number** on comment - Create an issue if not exist
1. Push your change
1. Test all on cloud

**NB**:
* I list  script in package.json file 
* Command is :  npm run <name of script> from angular-mns folder
* YOU DO NOT have to change something in docs folder: files gets SHA , change is done with script only

**Comment by idrice24** [comment]
now the project run successfully!!!
