### ISSUE TITLE
Implementation of http://localhost:8080/api/ in Backend

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/mns#65]
For our backend demo the followin link should works:

1. http://localhost:8080/api/
1. Just for dev
1. Just for geeting stuffs

**Comment by Ghislain1** [comment]
can you test this issue in your local pc  and tell me if  the implementation works

**Comment by idrice24** [comment]
usually it is http://localhost:8080/ that dev runs the apps locally

**Comment by Ghislain1** [comment]
usually it is http://localhost:8080/api  for WEB API
