### ISSUE TITLE
application.properties should use same data for all developers

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/MNS#69]
1. Alll developer should update this PostGresSQL with the same information:
1. Just describe how to same those information:
1. Suitable info are 
spring.datasource.url= jdbc:postgresql://localhost:5432/testdb?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=123456789

**Port Nummer - Username - password - database name**
or see application.properties file froms server

**Comment by idrice24** [comment]
i am not understanding what to do for this issue

**Comment by Ghislain1** [comment]
application.properties Stores how to reach  DB!!
 you have  to use the same setting

 you have configure your machine with the same !! see application.properties
