### ISSUE TITLE
Project name with capital letter MNS 

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/mns#72]
GIve 5 maven project with capital letter? in github
**

DO what other dev do

**Comment by idrice24** [comment]
yes it is in capital

**Comment by Ghislain1** [comment]
Must not  capital ltter

**Comment by Ghislain1** [comment]
check your own repository ..  NO capital letter

**Comment by Ghislain1** [comment]
Name of gitporject with java   should not a capital  letter

**Comment by Ghislain1** [comment]
idrice
meneteeforme
mentees

works fine !! So we have to write  java project name in github

**Comment by idrice24** [comment]
mean i have to rename the project to small letters?

**Comment by Ghislain1** [comment]
Github not !!! Change it in Githbu too

**Comment by idrice24** [comment]
meneteeforme and mentees are wrong repositories. i will remove them

**Comment by Ghislain1** [comment]
Commit comment should MUST get issue number .. if you have no  issue, create one before commit it

**Comment by Ghislain1** [comment]
meneteeforme and mentees are wrong repositories. That is not important..   name is not Capital.. 
that 's what itry to say

**Comment by idrice24** [comment]
ok

**Comment by Ghislain1** [comment]
GOD !!!

**Comment by Ghislain1** [comment]
Respect development process for client ( see ReadMe file )
DO NOT  push change just like that...

**Comment by Ghislain1** [comment]
DONE
