### ISSUE TITLE
Add: Click here to see the Demo Live for  web API in readme

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/mns#76]
See in read me file :
 Click here to seee the Demo Live

Same to wep api with link
 this should return a json  response !!

**Comment by idrice24** [comment]
please can send me a refer link project 
i am not understanding how to do it

**Comment by Ghislain1** [comment]
Repro steps:
1. Go to readme file on github
1. Click on **Live RESTFul API** link
1. See what  happens

**Expected:** The browser should display a json information from heroku ---> This mean backend api works on cloud
Same thing with client

if everything ok close the issue!!
