### ISSUE TITLE
Package name  com.idrice24.MNS should be chanaged

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/MNS#9]
Due to requirement package name  should  get  form:
1. org.mns237.server
1. org.mns237.entity
<org>.<mns237>.dao
<org>.<mns237>.controller

see 
https://github.com/corona-warn-app/cwa-server/blob/master/services/submission/src/main/java/app/coronawarn/server/services/submission/ServerApplication.java

**Comment by idrice24** [comment]
done!!!

**Comment by Ghislain1** [comment]
Can you add a commit value whrere is done?
