### ISSUE TITLE
Compodoc inside your project

### ISSUE THREAD

**Issue by Ghislain1** [idrice24/mns#99]
Todos:
1. Why do we use compodoc tool?
1.   Use Compodoc inside your project

References:
1. [Compodoc Demo TodoMVC Angular](https://compodoc.github.io/compodoc-demo-todomvc-angular/index.html)
1. [Angular Training Compodoc](https://compodoc.app/guides/tutorial.html)

**Comment by idrice24** [comment]
what should i put in the documentation file?

**Comment by Ghislain1** [comment]
Nothing!!
It s done by itself.. 

You can close this issue.. It works fine
